### ISSUE TITLE
abgewiesenes SSL-Zertifikat

### ISSUE THREAD

**Issue by thofei** [w-marco/moneymoney-suresse#1]
Hallo Marco,

ich habe versucht mein Tagesgeld-Konto bei Suresse über deine Extension einzubinden, stosse aber auf folgenden Fehler. Irgendeine Idee woran das scheitern mag? Ich verwende Ventura 13.4.

Ein anderes Konto (bei der Hypovereinsbank) funktioniert problemlos.

> 11:59:34  Starting account setup assistant.
> 12:07:37  Lade Kontenliste ...
>           Web Banking Engine: Using user-supplied extension suresse.lua version 1.00.
>           Protocol version: Web Scraping
>           Server address: https://secure.suressedirektbank.de
>           Sending: POST https://secure.suressedirektbank.de/xclde/webapi/login/1/usersession
> 12:07:38  CFReadStream Error Domain=NSOSStatusErrorDomain Code=-9807 "errSSLXCertChainInvalid: Invalid certificate chain " UserInfo={_kCFStreamErrorCodeKey=-9807, _kCFStreamErrorDomainKey=3}
>           The SSL certificate of the server has an invalid issuer.
>           Das SSL-Zertifikat des API-Servers Ihrer Bank wurde von macOS 13.4 als ungültig abgewiesen. Bitte versuchen Sie es später noch einmal oder wenden Sie sich für weitere Informationen an den Support Ihrer Bank.  API-Server-Adresse: https://secure.suressedirektbank.de/xclde/webapi/login/1/usersession
> 12:13:01  Canceled account setup assistant.

**Comment by w-marco** [comment]
Hallo @thofei,

also ich habe hier Ventura 13.4.1 und bei mir klappt es. 
Deine Systemuhrzeit + Datum sind korrekt eingestellt?

Kannst du im macOS-Terminal mal folgenden Befehl ausführen und den Output hier posten?

`curl -vI https://secure.suressedirektbank.de/xclde/webapi/login/1/usersession`


Weil eigentlich ist das Zertifikat bis Oktober gültig und alles sieht normal aus.

**Comment by thofei** [comment]
Hallo Marco,

Curl hat den gleichen Fehler gebracht und ich habe in der Zwischenzeit auch herausgefunden warum das in meinem Falle auftrat (falls jemand anderes in das gleiche Problem stolpert):

Ich bin hier im Firmennetzwerk unterwegs und die Firewall der Firma macht eine SSL Inspection zum überprüfen der Dateien, was prinzipiell bedeutet, dass das originale Zertifikat aufgebrochen wird und die Firewall nach dem Check temporär ein eigenes Zertifikat einbaut. Das stimmt dann natürlich nicht mehr mit dem originalen Zertifikat überein und das stört gerade Bankingsoftware wohl viel mehr als z.B. normales Surfen über den Browser.

Einfach kurz in das Gäste-WLAN gewechselt, da findet diese SSL Inspection nicht statt und schon konnte ich die Suresse Bank problemlos einbinden.


Vielen Dank für deine schnelle Rückmeldung.
